Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -25,3 +25,7 @@ jobs:
    - name: Run testbench
      run: |
        vvp -v compiled_test_bench -mtest_bench
+       if [ $? -ne 0 ]; then
+         echo "Tests failed"
+         exit 1
+       fi
